repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-added-large-files
    - id: trailing-whitespace
- repo: https://github.com/lietu/go-pre-commit
  rev: v0.1.0
  hooks:
    # - id: errcheck
    - id: go-fmt-goimports
    - id: go-test
    - id: go-vet
    - id: golint
    - id: staticcheck
    - id: go-mod-tidy