name: Go

on:
  push:
    branches: [ "main" ]

jobs:
  validate_prod_push:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.19', '1.20', '1.21.x', '1.22.x']

    steps:
    - uses: actions/checkout@v4
    - name: Make .env file
      id: makeenv
      uses: ozaytsev86/create-env-file@v1
      with:
        ENV_APCA_API_KEY_ID: ${{ secrets.APCA_API_KEY_ID }}
        ENV_APCA_API_SECRET_KEY: ${{ secrets.APCA_API_SECRET_KEY }}
        ENV_ENDPOINT: ${{ secrets.ENDPOINT }}
    - name: Set up Go
      if: steps.makeenv.outcome == 'success'
      id: goconfig
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Run Go build
      if: steps.goconfig.outcome == 'success'
      id: gobuild
      run: go build -v ./...
    - name: Run Go tests
      if: steps.gobuild.outcome == 'success'
      id: gotest
      run: go test -v ./...



    # - shell: bash
    #   env:
    #     APCA_API_KEY_ID: ${{ secrets.APCA_API_KEY_ID }}
    #   run: echo -e "$APCA_API_KEY_ID"


  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Create env
  #     uses: actions/checkout@v4
  #     with:
  #       APCA_API_KEY_ID: ${{ secrets.APCA_API_KEY_ID }}
  #       repo_token: ${{ secrets.GITHUB_TOKEN }}
  #     run: |
  #       echo -e "APCA_API_KEY_ID=${{ secrets.APCA_API_KEY_ID }}"



# jobs:
#   create-envfile:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Make envfile
#       uses: SpicyPizza/create-envfile@v2.0
#       with:
#         envkey_APCA_API_KEY_ID: ${{ secrets.APCA_API_KEY_ID }}
#         envkey_APCA_API_SECRET_KEY: ${{ secrets.APCA_API_SECRET_KEY }}
#         envkey_ENDPOINT: ${{ secrets.ENDPOINT }}
#         file_name: .env
#         fail_on_empty: false
#         sort_keys: false

#   build:
#     needs: create-envfile
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         go-version: ['1.22.3']
#         # os: [ubuntu-latest, macos-latest, windows-latest]
#         # go-version: ['1.19', '1.20', '1.21.x', '1.22.x']
#     steps:
#     - uses: actions/checkout@v4
#     - name: Set up Go
#       uses: actions/setup-go@v4
#       with:
#         go-version: ${{ matrix.go-version }}
#         # go-version: 1.22
#     - name: Build
#       run: go build -v ./...
#     - name: Run tests
#       run: go test -v ./...

#   runs:
#     using: "composite"




    # runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     go-version: ['1.22.3']
    #     # os: [ubuntu-latest, macos-latest, windows-latest]
    #     # go-version: ['1.19', '1.20', '1.21.x', '1.22.x']
    # steps:
    # - uses: actions/checkout@v4
    # - name: Set up Go
    #   uses: actions/setup-go@v4
    #   with:
    #     go-version: ${{ matrix.go-version }}
    #     # go-version: 1.22
    # - name: Build
    #   run: go build -v ./...
    # - name: Run tests
    #   run: go test -v ./...



  # create-envfile:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Make envfile
  #     uses: SpicyPizza/create-envfile@v2.0
  #     with:
  #       envkey_APCA_API_KEY_ID: ${{ secrets.APCA_API_KEY_ID }}
  #       envkey_APCA_API_SECRET_KEY: ${{ secrets.APCA_API_SECRET_KEY }}
  #       envkey_ENDPOINT: ${{ secrets.ENDPOINT }}
  #       file_name: .env
  #       fail_on_empty: false
  #       sort_keys: false

  # test:
  #   needs: create-envfile
  #   runs-on: ubuntu-latest
  #   - name: Run tests
  #     run: go test -v ./...


# jobs:

#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         go-version: ['1.22.3']
#         # go-version: ['1.19', '1.20', '1.21.x', '1.22.x']

#     steps:
#     - uses: actions/checkout@v4
#     - name: Set up Go
#       uses: actions/setup-go@v4
#       with:
#         go-version: ${{ matrix.go-version }}
#         # go-version: 1.22

#     - name: Build
#       run: go build -v ./...

#     - name: Make envfile
#       uses: SpicyPizza/create-envfile@v2.0
#       with:
#         envkey_APCA_API_KEY_ID: ${{ secrets.APCA_API_KEY_ID }}
#         envkey_APCA_API_SECRET_KEY: ${{ secrets.APCA_API_SECRET_KEY }}
#         envkey_ENDPOINT: ${{ secrets.ENDPOINT }}
#         file_name: .env
#         fail_on_empty: false
#         sort_keys: false

#     - name: Test
#       run: go test -v ./...

    # - name: Display Go version
    #   run: go version

    # - name: Build
    #   run: go build -v ./...

    # - name: Test
    #   run: go test -v ./...



    # - name: Create env
    # run: |
    #   echo -e "APCA_API_KEY_ID=${{ secrets.APCA_API_KEY_ID }} \n \
    #   APCA_API_SECRET_KEY=${{ secrets.APCA_API_SECRET_KEY }} \n \
    #   ENDPOINT=${{ secrets.ENDPOINT }}" >> .env